version: '3.4'
services:
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: ../
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"

  redis:
    image: redis
    container_name: redis
    hostname: redis_api
    networks:
      - prod
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql_api
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=go_api
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=go_api
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - prod
    expose:
      - '6379'

networks:
  prod:
    driver: bridge